version: 2

sources:
  - name: UrbanMove_raw
    description: "Les données brutes de France mobilités"
    tables:
      - name: accessibilite_gare
        description: "niveau d'accessibilité des gares"
      - name: arrets_lignes
        description: "Les données des arrêts de transport"
      - name: horaires
        description: "Données de retard par jour, par heure et par ligne"
      - name: indicateurs_perception
        description: "Note de satisfaction des usagers sur certaines lignes"
      - name: liste_transporteurs
        description: "Liste des différents opérateurs"
      - name: nb_fer
        description: "Nombre de validation de titre de transport par jour et par arrêt pour le réseau ferré"
      - name: nb_surface
        description: "Nombre de validation de titre de transport par jour et par ligne pour le réseau surface"
      - name: profil_fer
        description: "Pourcentage de validations par tranche horaire et par arrêt pour le réseau ferré"
      - name: profil_surface
        description: "Pourcentage de validations par tranche horaire et par ligne pour le réseau surface"
      - name: referentiel_des_lignes
        description: "Données détaillées sur les lignes"
      - name: stops
        description: "Données détaillées des arrêts mais table qui sert surtout pour faire le lien entre id_ligne et id_arrêt"



models:
  - name: trajets_summary
    description: "Résumé des trajets avec le nombre de trajets et le montant total par segment de client et type de véhicule."
    columns:
      - name: segment_client
        description: "Le segment auquel appartient le client (ex : Particulier, VIP, Entreprise)."
        tests:
          - not_null
      - name: type_vehicule
        description: "Le type de véhicule utilisé pour le trajet (ex : Berline, SUV)."
        tests:
          - not_null
      - name: nombre_trajets
        description: "Le nombre total de trajets effectués pour ce type de véhicule et ce segment de client."
      - name: total_revenus
        description: "Le montant total des revenus générés par les trajets pour ce type de véhicule et ce segment de client."


  - name: revenus_par_segment_et_type
    description: "Modèle qui calcule le nombre total de trajets et le montant total des revenus par segment de client et type de véhicule."
    columns:
      - name: segment_client
        description: "Le segment de client (Entreprise, VIP, Particulier)."
      - name: type_vehicule
        description: "Le type de véhicule (SUV, Berline)."
      - name: nombre_trajets
        description: "Le nombre de trajets réalisés pour ce type de véhicule et ce segment."
      - name: total_revenus
        description: "Le montant total des revenus générés par ce type de véhicule et ce segment."

  - name: stg_faits_trajets
    description: "Modèle de staging reliant les trajets et la dimension dates."
    tests:
      - freshness_by_max_date:
          arguments:
            threshold_days: 2
          config:
            severity: warn
      - freshness_by_max_date:
          arguments:
            threshold_days: 3
          config:
            severity: error